name: Hello World!

on: 
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: windows-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
        shell: bash
      - name: Now it is
        run: |
          date
        shell: bash
      - name: Directory content
        run: |
          ls -l
        shell: bash
